docs/extra.css

The magnifier icon for searching repeats on IE 11

Fixed a style issue

---

docs/making_calls.md

Update voice calls info for:
1. Setting Caller ID value for RingOut API
1. URI Scheme usage for Google Chrome

Minor updates for URI Scheme and Caller ID

---

docs/active_call_control_overview.md
docs/active_call_control_quick_start.md

Added Description to Call Control Sections. Please review and update it so that, I can share it with the customers.

Added Description to Call Control Sections

---

docs/sms/tutorials/sending-sms.md
docs/sms/tutorials/valid-sms-numbers.md

Update Developer Manual for Valid SMS Numbers and Sending SMS.

Bootstrap vertical nav

---

mkdocs.yml
redirection/main.html

new developer guide had been released, need to redirect the old to the new

DPW developer guide redirection

---

docs/authentication/quick-start/authorization-flow/c-sharp.md
docs/notifications/quick-start/webhook/c-sharp.md

Add C# OAuth tutorial & WebHook tutorial

---

docs/voice/presence.md
mkdocs.yml

Moved presence under Voice. Presence is not a top-level API or API Product.

Refactored the Presence API documentation

---

docs/sms/tutorials/message-store.md
docs/voice/presence.md

Added message store and presence

Added more Ruby

---

docs/authentication/quick-start/authorization-flow/c-sharp.md
docs/authentication/quick-start/authorization-flow/node.md
docs/authentication/quick-start/authorization-flow/php.md
docs/authentication/quick-start/authorization-flow/python.md
docs/authentication/quick-start/authorization-flow/ruby.md
docs/authentication/quick-start/index.md
docs/meetings/quick-start/index.md
docs/sms/quick-start/index.md
docs/voice/call-queues.md
docs/voice/quick-start/index.md
mkdocs.yml

- Added Authorization flow Ruby QS
- Removed authorization popup to simplify JavaScript code

Phong Updated

---

docs/authentication/quick-start/authorization-flow/node.md

https://github.com/ringcentral/ringcentral-js/blob/master/src/platform/Platform.js#L174

authUrl had been renamed to loginUrl

---

docs/voice/supervision.md

Added the SIP Invite Sample

---

docs/voice/supervision.md

Extended Call Monitoring Groups with additional documentation

Extended Call Monitoring Groups with additional documentation

---

docs/voice/supervision.md

Updated based on changes

---

docs/meetings/quick-start.md
docs/messaging/quick-start.md
docs/notifications/push-notifications/quick-start.md
docs/team-messaging/manual/compliance-export.md
docs/team-messaging/quick-start.md
docs/voice/quick-start.md
docs/voice/ringout.md

- Use latest Java SDK
- Use latest .Net SDK
- Add server constants

Fixed and updated Java code

---

docs/messaging/sms/high-volume/toll-free-sms-vs-local-numbers.md
docs/messaging/sms/high-volume/valid-a2p-sms-numbers.md
mkdocs.yml

- Merge Toll-Free/local number page with valid SMS number page
- Remove the valid A2P sms number page and option from the menu

Phong update

---

docs/voice/call-control-sessions.md

Added some missing letters and replaced a hyphen with an em dash.

A good proofread

---

docs/index.md

Added High Volume SMS under SMS

Added High Volume SMS under SMS

---

docs/messaging/sms/high-volume/index.md

"Scheduling" was causing some confusion, clarified to mean scheduling of SMS

Clarified what type of scheduling is not allowed

---

docs/messaging/sms/best-practices.md

I was reading through the SMS Best Practices and noticed some spelling mistakes.

Fixes spelling mistakes in the sms best practices

---

code-samples/voice/call-queues-enable-member-status-editable.js
code-samples/voice/call-queues-enable-member-status-editable.py
code-samples/voice/call-queues-read-call-queues.js
code-samples/voice/call-queues-read-call-queues.py
code-samples/voice/call-queues-read-member-status-editable.js
code-samples/voice/call-queues-read-member-status-editable.py
code-samples/voice/call-queues-read-member-status.js
code-samples/voice/call-queues-read-member-status.py
code-samples/voice/call-queues-update-extension-dnd.js
code-samples/voice/call-queues-update-extension-dnd.py
code-samples/voice/call-queues-update-extension-status.js
code-samples/voice/call-queues-update-extension-status.py
code-samples/voice/call-queues-update-member-status.js
code-samples/voice/call-queues-update-member-status.py
docs/messaging/sms/sending-sms.md
docs/voice/call-routing/index.md
docs/voice/call-routing/manual/call-queues-presence.md
docs/voice/call-routing/manual/call-queues.md
mkdocs.yml

- Added Call queue presense API dev guide and sampe codes

Phong's update

---

docs/team-messaging/manual/node.md

It looks like the message type changed, please update.

update message type

---

docs/messaging/sms/high-volume/sending-highvolume-sms.md

Since the Java SDK was updated, code snippet needed to be changed as the old snippet became incorrect due to API naming changes etc.

Updated Java Code Snippets

---

docs/account/presence.md

Just fixed code blocks because it was breaking the UI

Fixed markdown in presence.md

---

docs/provisioning/location/emergency-locations.md
mkdocs.yml

@byrnereese please review this draft.

Initial draft for emergency locations

---

code-samples/java-samples/src/main/java/com/ringcentral/AuthorizationFlow.java
docs/authentication/quick-start.md

Fixed the OAuth Java code sample that was previously using Password flow instead of AuthCode Flow and older dependencies and SDK. Tested to verify the correct behavior.

Fixed OAuth Flow Java Code sample and instructions

---

docs/analytics/quick-start.md

Fixed https://jira.ringcentral.com/browse/DPW-17640 bug.

Updated sample code and resolved the bug

---

.markdownlint-cli2.cjs
.markdownlint/customRules/helpers/addError.js
.markdownlint/customRules/helpers/filterTokens.js
.markdownlint/customRules/helpers/index.js
.markdownlint/customRules/rules/html-images.js
.markdownlint/customRules/rules/html-links.js
.markdownlint/customRules/rules/md-images.js
.markdownlint/customRules/rules/md-links.js
.markdownlint/rules/index.cjs
docs/address-book/index.md
docs/basics/explorer.md

1. Add Markdown Linter Setting Files
2. Fix Some Linter Issues

ADD Markdown Linter

---

docs/social-messaging/index.md

Removing references to Digital Inbox, and making it generic after discussion with Paco and Jeba.

Removing references to Digital Inbox, and making it generic after discussion with Paco and Jeba.

---

code-samples/voice/ReadUserCallLog.java
code-samples/voice/call-log.cs
docs/social-messaging/index.md

- Fixed call log sample code indents
- Changed RingEX license term

Minor fixes

---

code-samples/account/create-user.js
code-samples/account/presence.cs
code-samples/meetings/quick-start.cs
code-samples/voice/Call_RingOut/Program.cs
code-samples/voice/call-forwarding.cs
code-samples/voice/call-log.cs
code-samples/voice/call-queues.cs
code-samples/voice/call-routing.cs
code-samples/voice/company-answering-rules.cs
code-samples/voice/finding-active-calls.cs
code-samples/voice/user-answering-rules.cs
docs/social-messaging/quick-start.md

- Fixed broken links in SM quick started
- Fixed .NET sample code async functions

Quick fixes

---

code-samples/messaging/code-snippets/create-user-sms-tempate.rb
code-samples/messaging/code-snippets/create-user-sms-template.js
code-samples/messaging/code-snippets/create-user-sms-template.php
code-samples/messaging/code-snippets/create-user-sms-template.py
code-samples/video/meetings.cs
code-samples/video/meetings.java
code-samples/video/meetings.js
code-samples/video/meetings.php
code-samples/video/meetings.py
code-samples/video/meetings.rb
code-samples/webhooks/webhook-server.js
code-samples/webhooks/webhook-server.py
docs/messaging/quick-start.md
docs/messaging/templates/overview.md
mkdocs.yml

- Added SMS template dev guide
- Fixed webhooks sample code local port
- Fixed video meeting sample code for all languages.

New dev guide and fixed items

---

code-samples/messaging/code-snippets/create-user-sms-template.cs
code-samples/messaging/code-snippets/create-user-sms-template.java
docs/messaging/quick-start.md
docs/messaging/templates/overview.md

- .NET sample code
- Java sample code

Update messaging template dev guide

---

mkdocs.yml

To be consistent with API reference

Changed "Notifications and events" to "Events and notifications"

---

docs/authentication/auth-code-flow.md
docs/authentication/auth-code-pkce-flow.md
docs/authentication/index.md
docs/authentication/jwt-flow.md
docs/authentication/jwt/jwt-for-public-apps.md
docs/authentication/jwt/quick-start.md
docs/authentication/jwt/troubleshooting.md
docs/authentication/oauth-request.md
docs/authentication/quick-start.md
docs/authentication/refresh-tokens.md
docs/authentication/tokens.md
docs/basics/errors.md
docs/basics/formats/objects.md
docs/basics/formats/resources.md
docs/basics/formats/responses.md
docs/basics/localization.md
docs/basics/permissions.md
docs/basics/rate-limits.md
docs/basics/uris.md

Various corrections across the article.

Many corrections across Using the API section of Developer's Guide
